# Generated by Django 4.2.21 on 2025-06-03 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('name', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('name', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('name', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cooks', models.ManyToManyField(to='cooks.cook')),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dishtype')),
                ('ingredients', models.ManyToManyField(to='dishes.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
